<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Natália Neborásková">

<title>Vzťah medzi HDP a tvorbou investícií</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="ekonometriaprojekt_files/libs/clipboard/clipboard.min.js"></script>
<script src="ekonometriaprojekt_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="ekonometriaprojekt_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="ekonometriaprojekt_files/libs/quarto-html/popper.min.js"></script>
<script src="ekonometriaprojekt_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="ekonometriaprojekt_files/libs/quarto-html/anchor.min.js"></script>
<link href="ekonometriaprojekt_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ekonometriaprojekt_files/libs/quarto-html/quarto-syntax-highlighting-d9589ad4e98504035195c70aa99e1e7d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="ekonometriaprojekt_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="ekonometriaprojekt_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="ekonometriaprojekt_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Vzťah medzi HDP a tvorbou investícií</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Natália Neborásková </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="vzťah-medzi-hdp-a-tvorbou-investícií---taliansko" class="level1">
<h1>Vzťah medzi HDP a tvorbou investícií - Taliansko</h1>
<p>Model s korekčným členom (Error Correction Model, ECM) je ekonometrický nástroj využívaný na modelovanie dlhodobých rovnovážnych vzťahov medzi nestacionárnymi časovými radmi a krátkodobej dynamiky odchýlok od tejto rovnováhy. Teoretickým základom ECM je koncept kointegrácie, ktorý zaviedli Engle a Granger (1987).</p>
<p>V našej analýze predpokladáme, že hrubá tvorba fixného kapitálu (investície) v Taliansku závisí od celkovej ekonomickej aktivity vyjadrenej prostredníctvom hrubého domáceho produktu (HDP):</p>
<p><span class="math display">\[
INVEST=f(HDP)
\]</span></p>
<p><strong>HDP</strong> – predstavuje celkový výstup ekonomiky a hlavný determinant investičnej aktivity. Podľa teórie akcelerátora rastúci domáci produkt vyvoláva potrebu rozširovania výrobných kapacít, čo vedie k dodatočným investíciám. Zároveň vyššie HDP indikuje lepšiu ekonomickú kondíciu krajiny a vyššiu kúpyschopnosť, čo motivuje firmy k rozvoju → <strong>očakávam kladný vzťah.</strong></p>
<p><strong>Investície (Hrubá tvorba fixného kapitálu)</strong> -Investície v modeli vystupujú ako závislá premenná, ktorú sa snažíme vysvetliť pomocou vývoja HDP. V kontexte talianskej ekonomiky investície predstavujú kľúčový motor rastu, avšak sú vysoko senzitívne na hospodárske šoky a zmeny v očakávaniach podnikateľov. Očakávame, že investície budú vykazovať vyššiu volatilitu než samotné HDP, čo je typický znak tejto zložky agregátneho dopytu. Dlhodobý vzťah s HDP predpokladáme na základe teórie, že stabilný rast ekonomiky spätne stimuluje investičné výdavky do technológií a infraštruktúry.</p>
<p><strong>Mechanizmus korekcie chýb (ECT)</strong> – v modeli ECM predstavuje kľúčový prvok, ktorý prepája krátkodobé zmeny s dlhodobou rovnováhou. Ak v jednom období investície vzrastú nad úroveň zodpovedajúcu dlhodobému vzťahu s HDP, v nasledujúcom období ich mechanizmus korekcie chýb “stiahne” späť k rovnováhe. Koeficient pri tomto člene musí byť záporný a štatisticky významný, čo potvrdzuje schopnosť ekonomiky eliminovať nerovnováhy.</p>
<section id="údaje-popis-a-zdroje" class="level2">
<h2 class="anchored" data-anchor-id="údaje-popis-a-zdroje">Údaje – popis a zdroje</h2>
<p>Analýza využíva štvrťročné dáta pre Taliansko za obdobie <strong>2005Q1 – 2025Q4</strong>. Všetky premenné boli získané z databázy Eurostatu. Dáta boli stiahnuté vo formáte .xlsx a následne importované do prostredia R pre ďalšie spracovanie. Obdobie bolo zvolené tak, aby zachytilo dlhodobý vývoj investičnej aktivity vrátane významných hospodárskych cyklov.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Premenná</strong></td>
<td><strong>Popis</strong></td>
<td><strong>Zdroj</strong></td>
</tr>
<tr class="even">
<td><strong>hdp</strong></td>
<td>Hrubý domáci produkt (reálny index, sezónne očistený)</td>
<td>Eurostat</td>
</tr>
<tr class="odd">
<td><strong>invest</strong></td>
<td>Hrubá tvorba fixného kapitálu (reálny index, sezónne očistená)</td>
<td>Eurostat</td>
</tr>
</tbody>
</table>
<p>Dáta reprezentujú objemové indexy, čo umožňuje eliminovať vplyv inflácie a sledovať reálny rast oboch ukazovateľov. Pred samotnou analýzou boli premenné transformované na objekty časových radov (<code>ts</code>) s kvartálnou frekvenciou.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(seasonal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'seasonal' was built under R version 4.5.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(astsa)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'astsa'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:seasonal':

    trend, unemp</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forecast' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'forecast'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:astsa':

    gas</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(urca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'urca' was built under R version 4.5.2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.5.2
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ tibble::view()  masks seasonal::view()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dynlm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: zoo

Attaching package: 'zoo'

The following objects are masked from 'package:base':

    as.Date, as.Date.numeric</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Vplyv HDP na hrubú tvorbu fixného kapitálu (Investície)</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>italy <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"zadanie.xlsx"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">ts</span>(italy[, <span class="fu">c</span>(<span class="st">"HDP"</span>, <span class="st">"investicie"</span>)], <span class="at">start=</span><span class="dv">2005</span>, <span class="at">frequency =</span> <span class="dv">4</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)[<span class="dv">1</span>]<span class="ot">&lt;-</span><span class="st">"hdp"</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data)[<span class="dv">2</span>]<span class="ot">&lt;-</span><span class="st">"invest"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="dátový-prehľad" class="level2">
<h2 class="anchored" data-anchor-id="dátový-prehľad">Dátový prehľad</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Príprava dát pre ggplot (prevod z ts na dataframe)</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>data_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">time =</span> <span class="fu">as.numeric</span>(<span class="fu">time</span>(data)),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">hdp =</span> <span class="fu">as.numeric</span>(data[,<span class="st">"hdp"</span>]),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">invest =</span> <span class="fu">as.numeric</span>(data[,<span class="st">"invest"</span>])</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>data_long <span class="ot">&lt;-</span> data_df <span class="sc">%&gt;%</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">c</span>(hdp, invest), </span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"premenna"</span>, </span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"hodnota"</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_long, <span class="fu">aes</span>(<span class="at">x =</span> time, <span class="at">y =</span> hodnota, <span class="at">color =</span> premenna)) <span class="sc">+</span></span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> premenna, <span class="at">scales =</span> <span class="st">"free_y"</span>, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Vývoj premenných — Taliansko 2005Q1–2025Q4"</span>,</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Rok"</span>, </span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Index"</span>,</span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Zdroj: Vlastné spracovanie na základe údajov z Eurostatu"</span>) <span class="sc">+</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>        <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/vizualizacia-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>HDP (hdp)</strong> vykazuje počas sledovaného obdobia rastúci trend, ktorý bol však prerušený dvoma kľúčovými udalosťami. Prvým je globálna finančná kríza (2008–2009) a následná dlhová kríza v eurozóne, kedy talianska ekonomika zaznamenala stagnáciu a mierny pokles. Druhým, oveľa výraznejším výkyvom, je rok 2020 a pandémia COVID-19, kedy došlo k bezprecedentnému prepadu aktivity, po ktorom však nasledovalo relatívne rýchle oživenie.</p>
<p><strong>Investície (invest)</strong> sa vyvíjajú v úzkej korelácii s HDP, avšak s oveľa vyššou mierou volatility, čo potvrdzuje ekonomickú teóriu o citlivosti investičnej aktivity na šoky. Najväčší prepad je badateľný počas roku 2020. Na rozdiel od HDP, investície vykazujú ku koncu sledovaného obdobia (2024-2025) výraznejšie zrýchlenie, čo môže odrážať implementáciu národného plánu obnovy a odolnosti v Taliansku.</p>
</section>
<section id="analýza-stacionarity-adf-testy" class="level2">
<h2 class="anchored" data-anchor-id="analýza-stacionarity-adf-testy">Analýza stacionarity – ADF testy</h2>
<section id="hdp" class="level3">
<h3 class="anchored" data-anchor-id="hdp">HDP</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF a PACF#ACdataF a PACF</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(data[,<span class="dv">1</span>],<span class="dv">4</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]  [,4]
ACF  0.87 0.76 0.67  0.56
PACF 0.87 0.03 0.00 -0.10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtsdisplay</span>(data[,<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ljung box test</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>LjungBoxTest <span class="ot">&lt;-</span> <span class="cf">function</span>(res, <span class="at">k =</span> <span class="dv">0</span>, <span class="at">lag.max =</span> <span class="dv">30</span>, <span class="at">StartLag =</span> <span class="dv">1</span>, <span class="at">SquaredQ =</span> <span class="cn">FALSE</span>){</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(k <span class="sc">&gt;=</span> <span class="dv">0</span>, StartLag <span class="sc">&gt;=</span> <span class="dv">1</span>, lag.max <span class="sc">&gt;=</span> StartLag)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(res)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  L0 <span class="ot">&lt;-</span> StartLag</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (SquaredQ) {</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> (res <span class="sc">-</span> <span class="fu">mean</span>(res))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    kpar <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> res</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    kpar <span class="ot">&lt;-</span> k</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  ra <span class="ot">&lt;-</span> (<span class="fu">acf</span>(z, <span class="at">lag.max =</span> lag.max, <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>acf)[<span class="sc">-</span><span class="dv">1</span>]                       </span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>  lags <span class="ot">&lt;-</span> L0<span class="sc">:</span>lag.max                                                            </span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>  QQ <span class="ot">&lt;-</span> n <span class="sc">*</span> (n <span class="sc">+</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">cumsum</span>((ra<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n <span class="sc">-</span> (<span class="dv">1</span><span class="sc">:</span>lag.max)))[lags]                  </span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">pmax</span>(lags <span class="sc">-</span> kpar, <span class="dv">1</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>  pv <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(QQ, <span class="at">df =</span> df)</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag =</span> lags,</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> QQ,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df,</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> pv</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(out)</span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a><span class="fu">LjungBoxTest</span>(data[,<span class="dv">1</span>],<span class="at">lag.max =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lag statistic df      p.value
1   1  65.53129  1 5.551115e-16
2   2 116.39382  2 0.000000e+00
3   3 155.90974  3 0.000000e+00
4   4 183.99542  4 0.000000e+00</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">4</span>)   <span class="co">#9.487729</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.487729</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#alternativna funkcia pre Ljung-Box test</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(data[,<span class="dv">1</span>],<span class="at">lag=</span><span class="dv">4</span>,<span class="at">type=</span><span class="st">"Lj"</span>,<span class="at">fitdf =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  data[, 1]
X-squared = 184, df = 4, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#zaver-&gt; proces je NESTACIONARNY primame H1</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Dickeyho-fullerov test</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))                      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.8070  -0.4362   0.1027   0.4877   8.4499 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 15.21927    6.47017   2.352   0.0215 *
z.lag.1     -0.15951    0.06469  -2.466   0.0162 *
tt           0.03083    0.01400   2.203   0.0310 *
z.diff.lag  -0.04986    0.11826  -0.422   0.6746  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.236 on 69 degrees of freedom
Multiple R-squared:  0.1091,    Adjusted R-squared:  0.07037 
F-statistic: 2.817 on 3 and 69 DF,  p-value: 0.04543


Value of test-statistic is: -2.4656 2.5531 3.796 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">0</span>))                                      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.2109  -0.5098   0.1167   0.6219   9.8824 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 12.00089    5.64331   2.127   0.0365 *
z.lag.1     -0.11920    0.05520  -2.159   0.0338 *
tt           0.01295    0.01033   1.254   0.2136  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.143 on 80 degrees of freedom
Multiple R-squared:  0.05929,   Adjusted R-squared:  0.03577 
F-statistic: 2.521 on 2 and 80 DF,  p-value: 0.08675


Value of test-statistic is: -2.1594 1.7564 2.521 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co">#nie je vhodny</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co">#model s konstantou-drift-konstanta, pre model s driftom </span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"drift"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.0712  -0.5126   0.1649   0.6956   9.9889 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) 10.03556    6.19058   1.621    0.109
z.lag.1     -0.09579    0.05944  -1.612    0.112
z.diff.lag  -0.05107    0.12147  -0.420    0.675

Residual standard error: 2.297 on 70 degrees of freedom
Multiple R-squared:  0.04646,   Adjusted R-squared:  0.01922 
F-statistic: 1.705 on 2 and 70 DF,  p-value: 0.1892


Value of test-statistic is: -1.6116 1.3306 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.51 -2.89 -2.58
phi1  6.70  4.71  3.86</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"drift"</span>,<span class="at">lags=</span><span class="dv">0</span>))                                      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.8559  -0.4381   0.1756   0.6176  10.5126 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 10.31141    5.49935   1.875   0.0644 .
z.lag.1     -0.09779    0.05268  -1.856   0.0670 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.151 on 81 degrees of freedom
Multiple R-squared:  0.04081,   Adjusted R-squared:  0.02897 
F-statistic: 3.446 on 1 and 81 DF,  p-value: 0.06704


Value of test-statistic is: -1.8563 1.8358 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.51 -2.89 -2.58
phi1  6.70  4.71  3.86</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># nie je vhodny</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="co">#model bez trendu a konstanty</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"none"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.8960  -0.1714   0.1575   0.4924  10.9892 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1     0.000471   0.002612   0.180    0.857
z.diff.lag -0.105326   0.118098  -0.892    0.375

Residual standard error: 2.323 on 71 degrees of freedom
Multiple R-squared:  0.01138,   Adjusted R-squared:  -0.01647 
F-statistic: 0.4085 on 2 and 71 DF,  p-value: 0.6662


Value of test-statistic is: 0.1804 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">1</span>],<span class="at">type=</span><span class="st">"none"</span>,<span class="at">lags=</span><span class="dv">0</span>))      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
     Min       1Q   Median       3Q      Max 
-12.3346  -0.2070   0.1327   0.3748  12.2423 

Coefficients:
         Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1 0.0008932  0.0022961   0.389    0.698

Residual standard error: 2.184 on 82 degrees of freedom
Multiple R-squared:  0.001842,  Adjusted R-squared:  -0.01033 
F-statistic: 0.1513 on 1 and 82 DF,  p-value: 0.6983


Value of test-statistic is: 0.389 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prijmam H0 a tvrdime, že hdp je random walk - nestacionarny </span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co">#stacionarita diferencii</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">diff</span>(data[,<span class="dv">1</span>]),<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.3336  -0.4734   0.0951   0.5414   9.8039 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.72515    0.68403  -1.060    0.293    
z.lag.1     -1.22870    0.18091  -6.792 3.36e-09 ***
tt           0.01727    0.01350   1.279    0.205    
z.diff.lag   0.09403    0.12071   0.779    0.439    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.339 on 68 degrees of freedom
Multiple R-squared:  0.5654,    Adjusted R-squared:  0.5463 
F-statistic: 29.49 on 3 and 68 DF,  p-value: 2.498e-12


Value of test-statistic is: -6.7917 15.3759 23.0635 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">diff</span>(data[,<span class="dv">1</span>]),<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.1165  -0.3069   0.0690   0.5283  10.7421 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.200657   0.491344  -0.408    0.684    
z.lag.1     -1.107367   0.111708  -9.913 1.63e-15 ***
tt           0.007603   0.010302   0.738    0.463    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.203 on 79 degrees of freedom
Multiple R-squared:  0.5544,    Adjusted R-squared:  0.5431 
F-statistic: 49.14 on 2 and 79 DF,  p-value: 1.363e-14


Value of test-statistic is: -9.9131 32.7589 49.138 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model je vhodny a prva diferencia je stacionarna - Model je integrovaný prveho radu I(1)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Začíname modelom s trendom v tvare:</p>
<p><span class="math display">\[
\Delta HDP_t = \alpha_0 + \alpha_1 t + \delta HDP_{t-1} + u_i
\]</span></p>
<p>Výsledkom je model, v ktorom <span class="math inline">\(\phi_3 = 2.521\)</span> je menšie ako <span class="math inline">\(\phi_{3crit} = 6.49\)</span>. Nulovú hypotézu <span class="math inline">\(H_0: \delta = \alpha_1 = 0\)</span> nemôžeme na 5 % hladine významnosti zamietnuť a model s trendom nie je vhodný na testovanie.</p>
<p>Pokračujeme modelom s driftom (bez členov riešiacich autokoreláciu podľa BIC) v tvare:</p>
<p><span class="math display">\[
\Delta HDP_t = \alpha_0 + \delta HDP\_{t-1} + u_i
\]</span></p>
<p>Výsledkom je model, v ktorom <span class="math inline">\(\phi_1 = 1.8358\)</span> je menšie ako <span class="math inline">\(\phi_{1crit} = 4.71\)</span>. Nulovú hypotézu <span class="math inline">\(H_0: \delta = \alpha_0 = 0\)</span> nemôžeme na 5 % hladine významnosti zamietnuť a model s driftom nie je vhodný na testovanie.</p>
<p>Keďže ani model s trendom, ani model s driftom neboli vhodné, prechádzame k najjednoduchšiemu modelu bez deterministických zložiek:</p>
<p><span class="math display">\[
\Delta HDP_t = \delta HDP\_{t-1} + u_i\
\]</span></p>
<p>Hodnota testovacej štatistiky <span class="math inline">\(\tau_1 = 0.389\)</span> nie je menšia ako kritická hodnota <span class="math inline">\(\tau_{crit} = -1.95\)</span>. Prijímame nulovú hypotézu <span class="math inline">\(H_0: \delta = 0\)</span>, čo znamená, že časový rad HDP je <strong>nestacionárny</strong> a správa sa ako náhodná prechádzka. Na zistenie rádu integrácie pokračujeme testovaním prvých diferencií.</p>
<p>Model prvej diferencie s trendom má tvar:</p>
<p><span class="math display">\[
\Delta^2 HDP_t = \alpha_0 + \alpha_1 t + \delta \Delta HDP\_{t-1} + u_i
\]</span></p>
<p>Z výsledku vyplýva, že <span class="math inline">\(\phi_3 = 49.138\)</span> je výrazne väčšie ako <span class="math inline">\(\phi_{3crit} = 6.49\)</span>. Model s trendom je teda vhodný. Hodnota testovacej štatistiky <span class="math inline">\(\tau_3 = -9.9131\)</span> je menšia ako kritická hodnota <span class="math inline">\(\tau_{crit} = -3.45\)</span>, preto zamietame nulovú hypotézu o nestacionarite.</p>
<p><strong>Záver:</strong> Časový rad prvých diferencií HDP je stacionárny. Premenná HDP je teda integrovaná rádu jeden, <span class="math inline">\(HDP \sim I(1)\)</span>.</p>
</section>
<section id="investície-invest" class="level3">
<h3 class="anchored" data-anchor-id="investície-invest">Investície (invest)</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Investicie</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ACF a PACF#ACdataF a PACF</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">acf2</span>(data[,<span class="dv">2</span>],<span class="dv">4</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]  [,2]  [,3]  [,4]
ACF  0.95  0.90  0.84  0.79
PACF 0.95 -0.01 -0.07 -0.06</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtsdisplay</span>(data[,<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ljung box test</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">LjungBoxTest</span>(data[,<span class="dv">2</span>],<span class="at">lag.max =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lag statistic df p.value
1   1  78.30768  1       0
2   2 149.40129  2       0
3   3 212.89242  3       0
4   4 268.73416  4       0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">4</span>)   <span class="co">#9.487729</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.487729</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#alternativna funkcia pre Ljung-Box test</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Box.test</span>(data[,<span class="dv">2</span>],<span class="at">lag=</span><span class="dv">4</span>,<span class="at">type=</span><span class="st">"Lj"</span>,<span class="at">fitdf =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Box-Ljung test

data:  data[, 2]
X-squared = 268.73, df = 4, p-value &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co">#zaver-&gt; proces je NESTACIONARNY primame H1</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Dickeyho-fullerov test</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))                      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-17.8044  -1.6846   0.0578   1.2827  20.5562 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)  2.46041    3.65972   0.672  0.50364   
z.lag.1     -0.05048    0.03205  -1.575  0.11986   
tt           0.08027    0.02675   3.000  0.00375 **
z.diff.lag  -0.07110    0.11816  -0.602  0.54935   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.373 on 69 degrees of freedom
Multiple R-squared:  0.1199,    Adjusted R-squared:  0.08159 
F-statistic: 3.132 on 3 and 69 DF,  p-value: 0.03104


Value of test-statistic is: -1.5749 3.1716 4.6977 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">0</span>))                                        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.3414  -1.6124   0.1004   1.5011  22.9980 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)  0.90826    3.40766   0.267   0.7905  
z.lag.1     -0.01824    0.02752  -0.663   0.5092  
tt           0.03744    0.01967   1.903   0.0606 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.274 on 80 degrees of freedom
Multiple R-squared:  0.04597,   Adjusted R-squared:  0.02212 
F-statistic: 1.927 on 2 and 80 DF,  p-value: 0.1522


Value of test-statistic is: -0.663 1.3853 1.9273 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co">#nie je vhodny</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co">#model s konstantou-drift-konstanta, pre model s driftom nechame vybrat najvhodnejsi pocet lagov max 10-na zaklade schwarz kriteria(BIC)</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"drift"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.4347  -1.6255  -0.2185   1.7168  23.9945 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  2.45207    3.86322   0.635    0.528
z.lag.1     -0.01902    0.03197  -0.595    0.554
z.diff.lag   0.01007    0.12142   0.083    0.934

Residual standard error: 4.616 on 70 degrees of freedom
Multiple R-squared:  0.00504,   Adjusted R-squared:  -0.02339 
F-statistic: 0.1773 on 2 and 70 DF,  p-value: 0.8379


Value of test-statistic is: -0.5948 0.2304 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.51 -2.89 -2.58
phi1  6.70  4.71  3.86</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"drift"</span>,<span class="at">lags=</span><span class="dv">0</span>))                                        </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression drift 


Call:
lm(formula = z.diff ~ z.lag.1 + 1)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.5353  -1.6354  -0.0678   1.5342  23.9171 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
(Intercept)  1.86838    3.42421   0.546    0.587
z.lag.1     -0.01322    0.02783  -0.475    0.636

Residual standard error: 4.342 on 81 degrees of freedom
Multiple R-squared:  0.002778,  Adjusted R-squared:  -0.009533 
F-statistic: 0.2257 on 1 and 81 DF,  p-value: 0.636


Value of test-statistic is: -0.4751 0.2588 

Critical values for test statistics: 
      1pct  5pct 10pct
tau2 -3.51 -2.89 -2.58
phi1  6.70  4.71  3.86</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model nie je vhodny </span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="co">#model bez trendu a konstanty</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"none"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.1721  -1.8366  -0.0038   1.5258  24.4708 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1     0.001077   0.004456   0.242    0.810
z.diff.lag -0.003826   0.118925  -0.032    0.974

Residual standard error: 4.597 on 71 degrees of freedom
Multiple R-squared:  0.0008263, Adjusted R-squared:  -0.02732 
F-statistic: 0.02936 on 2 and 71 DF,  p-value: 0.9711


Value of test-statistic is: 0.2417 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(data[,<span class="dv">2</span>],<span class="at">type=</span><span class="st">"none"</span>,<span class="at">lags=</span><span class="dv">0</span>))      </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
     Min       1Q   Median       3Q      Max 
-15.2150  -1.6576   0.0968   1.3819  24.4633 

Coefficients:
        Estimate Std. Error t value Pr(&gt;|t|)
z.lag.1 0.001816   0.003857   0.471    0.639

Residual standard error: 4.324 on 82 degrees of freedom
Multiple R-squared:  0.002697,  Adjusted R-squared:  -0.009465 
F-statistic: 0.2217 on 1 and 82 DF,  p-value: 0.639


Value of test-statistic is: 0.4709 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prijmam H0 a tvrdime, že rgnp je random walk - nestacionarny </span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="co">#stacionarita diferencii</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">diff</span>(data[,<span class="dv">2</span>]),<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">10</span>,<span class="at">selectlags=</span><span class="st">"BIC"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.9171  -1.3703  -0.0454   1.3884  22.1428 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -2.880744   1.382475  -2.084   0.0409 *  
z.lag.1     -1.083929   0.178952  -6.057 6.76e-08 ***
tt           0.066635   0.027701   2.406   0.0189 *  
z.diff.lag  -0.005488   0.121085  -0.045   0.9640    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.483 on 68 degrees of freedom
Multiple R-squared:  0.5448,    Adjusted R-squared:  0.5247 
F-statistic: 27.13 on 3 and 68 DF,  p-value: 1.191e-11


Value of test-statistic is: -6.0571 12.2327 18.3441 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">diff</span>(data[,<span class="dv">2</span>]),<span class="at">type=</span><span class="st">"trend"</span>,<span class="at">lags=</span><span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression trend 


Call:
lm(formula = z.diff ~ z.lag.1 + 1 + tt)

Residuals:
     Min       1Q   Median       3Q      Max 
-16.5030  -1.3634   0.0534   1.6069  22.7657 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1.44961    0.96707  -1.499   0.1379    
z.lag.1     -1.05375    0.11196  -9.412 1.53e-14 ***
tt           0.04097    0.02044   2.005   0.0484 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.291 on 79 degrees of freedom
Multiple R-squared:  0.5286,    Adjusted R-squared:  0.5167 
F-statistic:  44.3 on 2 and 79 DF,  p-value: 1.252e-13


Value of test-statistic is: -9.4119 29.5331 44.2995 

Critical values for test statistics: 
      1pct  5pct 10pct
tau3 -4.04 -3.45 -3.15
phi2  6.50  4.88  4.16
phi3  8.73  6.49  5.47</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co">#model je vhodny a prva diferencia je stacionarna - Model je integrovaný prveho radu I(1)</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="do">######samotne premenné sú nestacionarne ale oba maju prvú diferenciu integrovanu prveho radu</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Na zistenie rádu integrácie premennej investícií použijeme rozšírený Dickeyho-Fullerov test (ADF). Postupujeme od najkomplexnejšieho modelu k najjednoduchšiemu.</p>
<p>Začíname modelom s trendom v tvare:</p>
<p><span class="math display">\[
\Delta INVEST_t = \alpha_0 + \alpha_1 t + \delta INVEST\_{t-1} + u_i\
\]</span></p>
<p>Výsledkom je model, v ktorom <span class="math inline">\(\phi_3 = 1.9273\)</span> je výrazne menšie ako kritická hodnota <span class="math inline">\(\phi_{3crit} = 6.49\)</span>. Nulovú hypotézu <span class="math inline">\(H_0: \delta = \alpha_1 = 0\)</span> nemôžeme na 5 % hladine významnosti zamietnuť a model s trendom nie je vhodný na testovanie.</p>
<p>Pokračujeme modelom s driftom v tvare:</p>
<p><span class="math display">\[
\Delta INVEST_t = \alpha_0 + \delta INVEST\_{t-1} + u_i
\]</span></p>
<p>Výsledkom je model, v ktorom <span class="math inline">\(\phi_1 = 0.2588\)</span> je menšie ako <span class="math inline">\(\phi_{1crit} = 4.71\)</span>. Nulovú hypotézu <span class="math inline">\(H_0: \delta = \alpha_0 = 0\)</span> nemôžeme na 5 % hladine významnosti zamietnuť a model s driftom nie je vhodný na testovanie stacionarity.</p>
<p>Prechádzame k modelu bez deterministických zložiek (none):</p>
<p><span class="math display">\[
\Delta INVEST_t = \delta INVEST\_{t-1} + u_i
\]</span></p>
<p>Hodnota testovacej štatistiky <span class="math inline">\(\tau_1 = 0.4709\)</span> nie je menšia ako kritická hodnota <span class="math inline">\(\tau_{crit} = -1.95\)</span>. Prijímame nulovú hypotézu <span class="math inline">\(H_0: \delta = 0\)</span>, čo znamená, že časový rad investícií je <strong>nestacionárny</strong> (obsahuje jednotkový koreň). Na určenie rádu integrácie testujeme prvú diferenciu radu.</p>
<p>Model prvej diferencie s trendom má tvar:</p>
<p><span class="math display">\[
\Delta^2 INVEST_t = \alpha_0 + \alpha_1 t + \delta \Delta INVEST_{t-1} + u_i
\]</span></p>
<p>Z výsledku vyplýva, že <span class="math inline">\(\phi_3 = 44.2995\)</span> je väčšie ako <span class="math inline">\(\phi_{3crit} = 6.49\)</span>. Model s trendom je teda vhodný. Hodnota testovacej štatistiky <span class="math inline">\(\tau_3 = -9.4119\)</span> je výrazne menšia ako kritická hodnota <span class="math inline">\(\tau_{crit} = -3.45\)</span>, čo nám umožňuje zamietnuť nulovú hypotézu o nestacionarite.</p>
<p><strong>Záver:</strong> Časový rad prvých diferencií investícií je stacionárny. Preto konštatujeme, že premenná investícií je integrovaná rádu jeden, teda <span class="math inline">\(invest \sim I(1)\)</span>.</p>
<p>Podmienky na tvorbu kointegračnej funkcie sú splnené.</p>
</section>
</section>
<section id="kointegračná-analýza-a-kointegračný-model" class="level2">
<h2 class="anchored" data-anchor-id="kointegračná-analýza-a-kointegračný-model">Kointegračná analýza a kointegračný model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co">#KOINTEGRACIA</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="co">#model dlhodobej rovnovahy-testovanie rezidualu, tabulky s kritickymi hodnotami</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Skumanie stacionarity rezidualu</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co">#skumajme hdp~i - dlhodoba rovnica</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>(coint<span class="ot">&lt;-</span><span class="fu">summary</span>(<span class="fu">lm</span>(hdp<span class="sc">~</span>invest,<span class="at">data=</span>data)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = hdp ~ invest, data = data)

Residuals:
    Min      1Q  Median      3Q     Max 
-9.4535 -1.0067  0.2347  1.4003  3.0047 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  75.9549     1.6292   46.62   &lt;2e-16 ***
invest        0.2327     0.0132   17.63   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.101 on 82 degrees of freedom
Multiple R-squared:  0.7913,    Adjusted R-squared:  0.7887 
F-statistic: 310.9 on 1 and 82 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">resid</span>(coint), <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">10</span>, <span class="at">selectlags =</span> <span class="st">"BIC"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1 + z.diff.lag)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.8835 -0.1440  0.2626  0.6901  4.2012 

Coefficients:
           Estimate Std. Error t value Pr(&gt;|t|)   
z.lag.1    -0.26605    0.08604  -3.092  0.00284 **
z.diff.lag  0.01435    0.11872   0.121  0.90415   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.411 on 71 degrees of freedom
Multiple R-squared:  0.1312,    Adjusted R-squared:  0.1067 
F-statistic: 5.359 on 2 and 71 DF,  p-value: 0.006798


Value of test-statistic is: -3.0923 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">ur.df</span>(<span class="fu">resid</span>(coint), <span class="at">type =</span> <span class="st">"none"</span>, <span class="at">lags =</span> <span class="dv">0</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
############################################### 
# Augmented Dickey-Fuller Test Unit Root Test # 
############################################### 

Test regression none 


Call:
lm(formula = z.diff ~ z.lag.1 - 1)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.9203 -0.2304  0.1863  0.6078  4.2950 

Coefficients:
        Estimate Std. Error t value Pr(&gt;|t|)    
z.lag.1 -0.24285    0.06935  -3.502 0.000751 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.318 on 82 degrees of freedom
Multiple R-squared:  0.1301,    Adjusted R-squared:  0.1195 
F-statistic: 12.26 on 1 and 82 DF,  p-value: 0.0007512


Value of test-statistic is: -3.5016 

Critical values for test statistics: 
     1pct  5pct 10pct
tau1 -2.6 -1.95 -1.61</code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-3.5016 &lt; -3,39 primame H1 -&gt; medzi premennymi  je kointegracia na 5% hladine vyznamnosti</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co">#model je kointegrovany</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Druhým krokom je odhad dlhodobého vzťahu medzi premennými metódou najmenších štvorcov (OLS). Táto rovnica predstavuje predpokladaný dlhodobý rovnovážny vzťah, ku ktorému premenné v čase smerujú.</p>
<section id="odhad-dlhodobej-rovnice" class="level4">
<h4 class="anchored" data-anchor-id="odhad-dlhodobej-rovnice">Odhad dlhodobej rovnice</h4>
<p>Odhadujeme vzťah, kde HDP závisí od investícií:</p>
<p><span class="math display">\[
HDP_t = \beta_0 + \beta_1 INVEST_t + \epsilon_t
\]</span></p>
<p>Z výsledkov OLS odhadu vyplýva, že investície majú štatisticky významný vplyv na HDP. Koeficient pri investíciách je <span class="math inline">\(0.2327\)</span>, čo interpretujeme tak, že pri raste investícií o jednu jednotku (indexu) vzrastie HDP dlhodobo o <span class="math inline">\(0.23\)</span> jednotky. Model vysvetľuje približne <span class="math inline">\(79\ \%\)</span> variability HDP (<span class="math inline">\(R^2 = 0.7913\)</span>).</p>
</section>
<section id="skúmanie-stacionarity-rezíduí-engle-grangerov-test" class="level4">
<h4 class="anchored" data-anchor-id="skúmanie-stacionarity-rezíduí-engle-grangerov-test">Skúmanie stacionarity rezíduí (Engle-Grangerov test)</h4>
<p>Aby sme overili, či ide o skutočnú kointegráciu a nie o zdanlivú regresiu, musíme otestovať stacionaritu rezíduí <span class="math inline">\(\epsilon_t\)</span> z tohto modelu pomocou ADF testu bez konštanty a trendu (typ “none”).</p>
<p>Výsledná hodnota testovacej štatistiky je <span class="math inline">\(\tau_1 = -3.5016\)</span>. Pri kointegrácii musíme použiť špeciálne kritické hodnoty podľa Engla a Grangera. Pre model s jednou vysvetľujúcou premennou je kritická hodnota na <span class="math inline">\(5\ \%\)</span> hladine významnosti približne <span class="math inline">\(-3.39\)</span> (prípadne <span class="math inline">\(-3.37\)</span> podľa MacKinnona).</p>
<p><strong>Záver:</strong> Keďže vypočítaná hodnota <span class="math inline">\(-3.5016\)</span> je v absolútnej hodnote väčšia ako kritická hodnota (<span class="math inline">\(|-3.50| &gt; |-3.39|\)</span>), nulovú hypotézu o nestacionarite rezíduí zamietame. Rezíduá sú stacionárne, čo potvrdzuje existenciu <strong>kointegračného vzťahu</strong> (dlhodobej rovnováhy) medzi HDP a investíciami.</p>
</section>
</section>
<section id="model-korekcie-chýb-ecm" class="level2">
<h2 class="anchored" data-anchor-id="model-korekcie-chýb-ecm">Model korekcie chýb (ECM)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Tvorba ECM modelu</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="co">#vlozime rezidual do nasej databazy</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>my_ts_data <span class="ot">&lt;-</span> <span class="fu">ts</span>(data, <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2005</span>, <span class="dv">1</span>), <span class="at">frequency=</span><span class="dv">4</span>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>res_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(<span class="fu">resid</span>(coint), <span class="at">start=</span><span class="fu">c</span>(<span class="dv">2005</span>, <span class="dv">1</span>), <span class="at">frequency=</span><span class="dv">4</span>)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>data_final <span class="ot">&lt;-</span> <span class="fu">ts.union</span>(my_ts_data, <span class="at">e =</span> stats<span class="sc">::</span><span class="fu">lag</span>(res_ts, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(data_final) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"hdp"</span>, <span class="st">"invest"</span>, <span class="st">"e"</span>)</span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a><span class="co"># zakladny model ECM - vybereme parametre kt. su ŠV</span></span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a>rovECM <span class="ot">&lt;-</span> <span class="fu">dynlm</span>(<span class="fu">d</span>(hdp) <span class="sc">~</span> <span class="fu">d</span>(invest) <span class="sc">+</span> <span class="fu">L</span>(e, <span class="dv">1</span>), <span class="at">data =</span> data_final)</span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rovECM) <span class="co">#vse ŠV</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Time series regression with "ts" data:
Start = 2005(3), End = 2025(4)

Call:
dynlm(formula = d(hdp) ~ d(invest) + L(e, 1), data = data_final)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.4130 -0.3724  0.1060  0.5659  2.2712 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.001157   0.120582  -0.010   0.9924    
d(invest)    0.426888   0.028092  15.196   &lt;2e-16 ***
L(e, 1)     -0.138652   0.057861  -2.396   0.0189 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.09 on 79 degrees of freedom
  (1 observation deleted due to missingness)
Multiple R-squared:  0.7593,    Adjusted R-squared:  0.7532 
F-statistic: 124.6 on 2 and 79 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#testovanie autokorelacie pomocou Ljung-Box</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>LjungBoxTest <span class="ot">&lt;-</span> <span class="cf">function</span>(res, <span class="at">k =</span> <span class="dv">0</span>, <span class="at">lag.max =</span> <span class="dv">30</span>, <span class="at">StartLag =</span> <span class="dv">1</span>, <span class="at">SquaredQ =</span> <span class="cn">FALSE</span>){</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stopifnot</span>(k <span class="sc">&gt;=</span> <span class="dv">0</span>, StartLag <span class="sc">&gt;=</span> <span class="dv">1</span>, lag.max <span class="sc">&gt;=</span> StartLag)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(res)</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>  L0 <span class="ot">&lt;-</span> StartLag</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (SquaredQ) {</span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> (res <span class="sc">-</span> <span class="fu">mean</span>(res))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>    kpar <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>    z <span class="ot">&lt;-</span> res</span>
<span id="cb84-11"><a href="#cb84-11" aria-hidden="true" tabindex="-1"></a>    kpar <span class="ot">&lt;-</span> k</span>
<span id="cb84-12"><a href="#cb84-12" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb84-13"><a href="#cb84-13" aria-hidden="true" tabindex="-1"></a>  ra <span class="ot">&lt;-</span> (<span class="fu">acf</span>(z, <span class="at">lag.max =</span> lag.max, <span class="at">plot =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>acf)[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb84-14"><a href="#cb84-14" aria-hidden="true" tabindex="-1"></a>  lags <span class="ot">&lt;-</span> L0<span class="sc">:</span>lag.max</span>
<span id="cb84-15"><a href="#cb84-15" aria-hidden="true" tabindex="-1"></a>  QQ <span class="ot">&lt;-</span> n <span class="sc">*</span> (n <span class="sc">+</span> <span class="dv">2</span>) <span class="sc">*</span> <span class="fu">cumsum</span>((ra<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n <span class="sc">-</span> (<span class="dv">1</span><span class="sc">:</span>lag.max)))[lags]</span>
<span id="cb84-16"><a href="#cb84-16" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">pmax</span>(lags <span class="sc">-</span> kpar, <span class="dv">1</span>)</span>
<span id="cb84-17"><a href="#cb84-17" aria-hidden="true" tabindex="-1"></a>  pv <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(QQ, <span class="at">df =</span> df)</span>
<span id="cb84-18"><a href="#cb84-18" aria-hidden="true" tabindex="-1"></a>  out <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb84-19"><a href="#cb84-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">lag =</span> lags,</span>
<span id="cb84-20"><a href="#cb84-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">statistic =</span> QQ,</span>
<span id="cb84-21"><a href="#cb84-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">df =</span> df,</span>
<span id="cb84-22"><a href="#cb84-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">p.value =</span> pv</span>
<span id="cb84-23"><a href="#cb84-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb84-24"><a href="#cb84-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(out)</span>
<span id="cb84-25"><a href="#cb84-25" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb84-26"><a href="#cb84-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-27"><a href="#cb84-27" aria-hidden="true" tabindex="-1"></a><span class="fu">LjungBoxTest</span>(<span class="fu">resid</span>(rovECM), <span class="at">lag.max =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   lag statistic df   p.value
1    1 0.9501079  1 0.3296918
2    2 1.3311713  2 0.5139724
3    3 1.4095111  3 0.7033068
4    4 1.4300502  4 0.8389557
5    5 4.3818794  5 0.4958414
6    6 6.6080640  6 0.3586174
7    7 7.2604003  7 0.4022801
8    8 7.6205124  8 0.4713888
9    9 7.6280033  9 0.5720246
10  10 7.6357621 10 0.6643667</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qchisq</span>(<span class="fl">0.95</span>,<span class="dv">10</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 18.30704</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co">#nemame autokorelaciu                                                           </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model ECM resid</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">resid</span>(rovECM), <span class="at">type=</span><span class="st">"l"</span>, <span class="at">col=</span><span class="st">"purple"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Keďže sme v predchádzajúcom kroku potvrdili existenciu kointegrácie, môžeme pristúpiť k odhadu modelu korekcie chýb. Tento model nám umožňuje analyzovať krátkodobú dynamiku HDP a zároveň sledovať, akou rýchlosťou sa systém vracia k dlhodobej rovnováhe po nečakanom šoku.</p>
<section id="špecifikácia-modelu" class="level3">
<h3 class="anchored" data-anchor-id="špecifikácia-modelu">Špecifikácia modelu</h3>
<p>Odhadujeme rovnicu v prvých diferenciách, kde vystupuje oneskorený korekčný člen (<span class="math inline">\(e_{t-1}\)</span>):</p>
<p><span class="math display">\[
\Delta HDP_t = \alpha + \beta_1 \Delta INVEST_t + \lambda e\_{t-1} + u_t
\]</span></p>
</section>
<section id="interpretácia-výsledkov" class="level3">
<h3 class="anchored" data-anchor-id="interpretácia-výsledkov">Interpretácia výsledkov</h3>
<p>Na základe výstupu z programu R môžeme zapísať odhadnutú rovnicu (konštantu vynechávame pre jej nevýznamnosť):</p>
<p><span class="math display">\[
\Delta HDP_t = 0.4269 \cdot \Delta INVEST_t - 0.1387 \cdot e\_{t-1}
\]</span></p>
<ol type="1">
<li><p><strong>Krátkodobá dynamika (</strong><span class="math inline">\(\beta_1\)</span>): Koeficient pri zmene investícií je <span class="math inline">\(0.4269\)</span> a je vysoko štatisticky významný. Znamená to, že ak v danom štvrťroku vzrastú investície o jednu jednotku, HDP v tom istom období vzrastie v priemere o <span class="math inline">\(0.43\)</span> jednotky.</p></li>
<li><p><strong>Rýchlosť návratu do rovnováhy (</strong><span class="math inline">\(\lambda\)</span>): Koeficient pri korekčnom člene (<span class="math inline">\(e_{t-1}\)</span>) je <span class="math inline">\(-0.1387\)</span> a je štatisticky významný na <span class="math inline">\(5\ \%\)</span> hladine významnosti (p-hodnota <span class="math inline">\(0.0189\)</span>).</p>
<ul>
<li><p>Záporné znamienko je kľúčové – potvrdzuje, že model je stabilný a vracia sa k rovnováhe.</p></li>
<li><p>Hodnota hovorí, že približne <span class="math inline">\(13.87\ \%\)</span> z nerovnováhy z predchádzajúceho obdobia sa skorigovalo v aktuálnom štvrťroku.</p></li>
</ul></li>
<li><p><strong>Kvalita modelu:</strong> Model vysvetľuje približne <span class="math inline">\(75.93\ \%\)</span> variability zmien HDP, čo je na model v diferenciách veľmi vysoká hodnota. F-štatistika (<span class="math inline">\(p &lt; 2.2 \times 10^{-16}\)</span>) potvrdzuje celkovú významnosť modelu.</p></li>
</ol>
</section>
<section id="diagnostika-test-autokorelácie" class="level3">
<h3 class="anchored" data-anchor-id="diagnostika-test-autokorelácie">Diagnostika: Test autokorelácie</h3>
<p>Pre overenie spoľahlivosti sme použili Ljung-Boxov test na rezíduá modelu ECM. Pri pohľade na p-hodnoty (v tvojich výsledkoch sú všetky výrazne nad <span class="math inline">\(0.05\)</span>) nezamietame nulovú hypotézu <span class="math inline">\(H_0\)</span>. Rezíduá nevykazujú autokoreláciu, čo znamená, že model je korektne špecifikovaný a získané koeficienty sú nestranné.</p>
</section>
</section>
<section id="prognóza-vývoja-hdp-na-rok-2026" class="level2">
<h2 class="anchored" data-anchor-id="prognóza-vývoja-hdp-na-rok-2026">Prognóza vývoja HDP na rok 2026</h2>
<p>Posledným krokom analýzy je vytvorenie krátkodobej predpovede (prognózy) vývoja HDP na nasledujúce štyri štvrťroky (rok 2026). Keďže pre exogénnu premennú (investície) nemáme k dispozícii externé predpovede, v modeli predpokladáme, že investície porastú svojím priemerným historickým tempom.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co">#prognoza</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. PRÍPRAVA ČISTÝCH VSTUPOV</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Použijeme na.omit, aby sme sa zbavili prípadných NA na konci dát</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>ciste_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(data_final)</span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>posledne_e <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">tail</span>(ciste_data[,<span class="st">"e"</span>], <span class="dv">1</span>))</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a>posledne_hdp <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">tail</span>(ciste_data[,<span class="st">"hdp"</span>], <span class="dv">1</span>))</span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Výpočet priemerného prírastku investícií bez NA hodnôt</span></span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>mean_d_invest <span class="ot">&lt;-</span> <span class="fu">mean</span>(<span class="fu">diff</span>(ciste_data[,<span class="st">"invest"</span>]), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. DYNAMICKÝ VÝPOČET PROGNÓZY (4 kroky)</span></span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a>prog_d_hdp <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">4</span>)</span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a>aktualne_e <span class="ot">&lt;-</span> posledne_e</span>
<span id="cb90-15"><a href="#cb90-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-16"><a href="#cb90-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>) {</span>
<span id="cb90-17"><a href="#cb90-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Používame koeficienty z tvojho modelu</span></span>
<span id="cb90-18"><a href="#cb90-18" aria-hidden="true" tabindex="-1"></a>  prog_d_hdp[i] <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.001157</span> <span class="sc">+</span> (<span class="fl">0.426888</span> <span class="sc">*</span> mean_d_invest) <span class="sc">+</span> (<span class="sc">-</span><span class="fl">0.138652</span> <span class="sc">*</span> aktualne_e)</span>
<span id="cb90-19"><a href="#cb90-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb90-20"><a href="#cb90-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aktualizácia rezídua pre ďalší krok (postupný návrat k rovnováhe)</span></span>
<span id="cb90-21"><a href="#cb90-21" aria-hidden="true" tabindex="-1"></a>  aktualne_e <span class="ot">&lt;-</span> aktualne_e <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.138652</span>)</span>
<span id="cb90-22"><a href="#cb90-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb90-23"><a href="#cb90-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-24"><a href="#cb90-24" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. PREPOČET NA REÁLNE HODNOTY HDP</span></span>
<span id="cb90-25"><a href="#cb90-25" aria-hidden="true" tabindex="-1"></a>prognoza_hdp_hodnoty <span class="ot">&lt;-</span> posledne_hdp <span class="sc">+</span> <span class="fu">cumsum</span>(prog_d_hdp)</span>
<span id="cb90-26"><a href="#cb90-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-27"><a href="#cb90-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Vytvorenie časového radu pre výsledky</span></span>
<span id="cb90-28"><a href="#cb90-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Ak tvoje dáta končia v 4. kvartáli 2025, prognóza začne 1. kvartálom 2026</span></span>
<span id="cb90-29"><a href="#cb90-29" aria-hidden="true" tabindex="-1"></a>prognoza_ts <span class="ot">&lt;-</span> <span class="fu">ts</span>(prognoza_hdp_hodnoty, </span>
<span id="cb90-30"><a href="#cb90-30" aria-hidden="true" tabindex="-1"></a>                  <span class="at">start =</span> <span class="fu">c</span>(<span class="dv">2026</span>, <span class="dv">1</span>), </span>
<span id="cb90-31"><a href="#cb90-31" aria-hidden="true" tabindex="-1"></a>                  <span class="at">frequency =</span> <span class="dv">4</span>)</span>
<span id="cb90-32"><a href="#cb90-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-33"><a href="#cb90-33" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. VÝPIS VÝSLEDKOV</span></span>
<span id="cb90-34"><a href="#cb90-34" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(prognoza_ts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Qtr1     Qtr2     Qtr3     Qtr4
2026 112.4626 112.4624 112.4761 112.5018</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graf pre vizuálnu kontrolu</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(prognoza_ts, <span class="at">type=</span><span class="st">"b"</span>, <span class="at">col=</span><span class="st">"pink"</span>, <span class="at">lwd=</span><span class="dv">2</span>, </span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Prognóza vývoja HDP (2026)"</span>, </span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"HDP"</span>, <span class="at">xlab=</span><span class="st">"Obdobie"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ekonometriaprojekt_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="metodika-výpočtu" class="level3">
<h3 class="anchored" data-anchor-id="metodika-výpočtu">Metodika výpočtu</h3>
<p>Prognóza je realizovaná dynamicky (rekurzívne). V každom kroku model vypočíta očakávanú zmenu HDP (<span class="math inline">\(\Delta HDP\)</span>) na základe:</p>
<ol type="1">
<li><p>Priemerného prírastku investícií.</p></li>
<li><p>Korekčného člena (<span class="math inline">\(e_{t-1}\)</span>), ktorý v každom kroku znižuje odchýlku od dlhodobej rovnováhy.</p></li>
</ol>
<p>Následne sú tieto zmeny (diferencie) pripočítané k poslednej známej hodnote indexu HDP z konca roka 2025.</p>
</section>
<section id="výsledky-prognózy" class="level3">
<h3 class="anchored" data-anchor-id="výsledky-prognózy">Výsledky prognózy</h3>
<p>V tabuľke nižšie sú uvedené predpovedané hodnoty indexu HDP pre jednotlivé štvrťroky roka 2026:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 60%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Obdobie (rok a štvrťrok)</strong></td>
<td><strong>Predpovedaná hodnota indexu (2015 = 100)</strong></td>
</tr>
<tr class="even">
<td>2026 Q1</td>
<td>112.46</td>
</tr>
<tr class="odd">
<td>2026 Q2</td>
<td>112.46</td>
</tr>
<tr class="even">
<td>2026 Q3</td>
<td>112.48</td>
</tr>
<tr class="odd">
<td>2026 Q4</td>
<td>112.50</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretácia-a-vizualizácia" class="level3">
<h3 class="anchored" data-anchor-id="interpretácia-a-vizualizácia">Interpretácia a vizualizácia</h3>
<p>Model predikuje stabilný vývoj s jemne rastúcim trendom v druhej polovici roka. Hodnota <strong>112.50</strong> v poslednom štvrťroku 2026 naznačuje, že HDP Nórska bude o <span class="math inline">\(12.50\ \%\)</span> vyššie v porovnaní so základným rokom 2015.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>